[global]
limits = { json = 5242880 }
daps_api_url = "http://omejdn"

[debug]
address = "0.0.0.0"
port = 8001
log_level = "normal"
limits = { forms = 32768 }
database_url = "mongodb://localhost:27017"
keyring_api_url = "http://localhost:8002"
clear_db = true

[release]
address = "0.0.0.0"
port = 8001
log_level = "normal"
limits = { forms = 32768 }
database_url = "mongodb://document-mongo:27017"
keyring_api_url = "http://keyring-api:8002"
clear_db = false
