# frozen_string_literal: true

source 'https://rubygems.org'

gem 'abstraction'
gem 'bcrypt'
gem 'haml'
gem 'json'
gem 'json-jwt'
gem 'jwt'
gem 'net-ldap'
gem 'openssl'
gem 'rack-test'
gem 'require_all'
gem 'rspec'
gem 'scanf'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-cors'
gem 'sqlite3'
gem 'test-unit'
gem 'thin'
gem 'webrick'
